# Generated by Django 6.0.2 on 2026-02-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_providerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='review_at',
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
