# Generated by Django 6.0.2 on 2026-03-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_serviceprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_rating',
        ),
    ]
