# Generated by Django 6.0.2 on 2026-03-10 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='total_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
