# Generated by Django 6.0.2 on 2026-03-10 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_serviceprovider_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
