# Generated by Django 6.0.2 on 2026-03-10 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_serviceprovider_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_photos/')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='accounts.serviceprovider')),
            ],
        ),
    ]
