# Generated by Django 6.0.2 on 2026-03-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Long Beach', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='California', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=33.7816133, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default=-118.1084064, null=True),
        ),
    ]
