# Generated by Django 6.0.2 on 2026-03-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_city_profile_state_alter_profile_latitude_and_more'),
        ('jobs', '0004_alter_job_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='favorited_jobs',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='jobs.job'),
        ),
    ]
