# Generated by Django 6.0.2 on 2026-03-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_serviceprovider_favorited_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
