# Generated by Django 5.2.11 on 2026-04-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_serviceprovider_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provider_document',
            field=models.FileField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='provider_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
