# Generated by Django 5.2.11 on 2026-04-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_language_profile_languages'),
        ('accounts', '0014_remove_profile_provider_document_providerapplication'),
    ]

    operations = [
    ]
