# Generated by Django 6.0.2 on 2026-04-24 05:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0021_merge_0012_alter_job_urgency_0020_alter_job_urgency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('customer_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_customer', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='jobs.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
