# Generated by Django 6.0.2 on 2026-04-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_rating',
        ),
        migrations.AddField(
            model_name='order',
            name='hired_for',
            field=models.TextField(blank=True),
        ),
    ]
