# Generated by Django 6.0.2 on 2026-04-04 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_serviceprovider_total_rating'),
        ('jobs', '0009_alter_job_latitude_alter_job_longitude'),
        ('reviews', '0003_reviewimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'job')},
        ),
    ]
