# Generated by Django 6.0.2 on 2026-04-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_latitude_alter_job_longitude'),
        ('reviews', '0004_alter_review_unique_together_review_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='jobs.job'),
        ),
    ]
