# Generated by Django 6.0.2 on 2026-03-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='request_type',
            field=models.CharField(choices=[('quote', 'Looking for Quote'), ('service', 'Perform Service'), ('both', 'Quote or Perform Service')], default='quote', max_length=20),
        ),
    ]
