# Generated by Django 6.0.2 on 2026-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_request_type'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='service',
        ),
        migrations.AddField(
            model_name='job',
            name='services',
            field=models.ManyToManyField(related_name='jobs', to='services.service'),
        ),
    ]
