# Generated by Django 6.0.2 on 2026-03-18 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_service_job_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
