# Generated by Django 6.0.2 on 2026-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_latitude_alter_job_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
