# Generated by Django 6.0.2 on 2026-04-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_language_profile_languages'),
        ('jobs', '0009_alter_job_latitude_alter_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.language'),
        ),
    ]
