# Generated by Django 5.2.11 on 2026-04-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_id_alter_jobimage_id'),
        ('jobs', '0009_alter_job_latitude_alter_job_longitude'),
    ]

    operations = [
    ]
