# Generated by Django 6.0.2 on 2026-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='urgency',
            field=models.CharField(choices=[('quote', 'Flexible'), ('service', 'Soon'), ('both', 'Urgent')], default='flexible', max_length=20),
        ),
    ]
