# Generated by Django 6.0.2 on 2026-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='urgency',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('soon', 'Soon'), ('urgent', 'Urgent')], default='flexible', max_length=20),
        ),
    ]
