# Generated by Django 5.2.11 on 2026-04-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_merge_20260407_0018'),
        ('jobs', '0011_job_urgency'),
    ]

    operations = [
    ]
