# Generated by Django 6.0.2 on 2026-04-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_merge_0010_merge_20260407_0018_0011_job_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='urgency',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('soon', 'Soon'), ('urgent', 'Urgent')], default='flexible', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
