# Generated by Django 6.0.2 on 2026-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
