# Generated by Django 6.0.2 on 2026-04-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_city_job_state_job_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='urgency',
            field=models.CharField(choices=[('Flexible', 'Flexible'), ('Soon', 'Soon'), ('Urgent', 'Urgent')], default='Flexible', max_length=20),
        ),
    ]
