# Generated by Django 6.0.2 on 2026-04-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_urgency'),
        ('jobs', '0020_alter_job_urgency'),
    ]

    operations = [
    ]
